org: dylancabezas
service: api-compras-2

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  memorySize: 1024
  timeout: 29
  iam:
    role: arn:aws:iam::744127473797:role/LabRole
    deploymentRole: arn:aws:iam::744127473797:role/LabRole
  environment:
    COMPRAS_TABLE: t_compras_${sls:stage}
    TOKENS_TABLE: t_tokens_acceso-${sls:stage}
    S3_BUCKET: farmacia-compras-dc-456-${sls:stage}
    GLUE_CRAWLER_NAME: compras-crawler-${sls:stage}

functions:
  RegistrarCompra:
    handler: src/RegistrarCompra.handler
    events:
      - http:
          path: compras/registrar
          method: post
          cors: true

  ListarCompras:
    handler: src/ListarCompras.handler
    events:
      - http:
          path: compras/listar
          method: get
          cors: true

  ActualizarCompras:
    handler: src/ActualizarCompras.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - ComprasDynamoDBTable
              - StreamArn
          batchSize: 1
          startingPosition: LATEST

  EjecutarCrawler:
    handler: src/EjecutarCrawler.handler
    events:
      - s3:
          bucket: farmacia-compras-dc-456-${sls:stage}
          event: s3:ObjectCreated:*
          rules:
            - prefix: compras/
            - suffix: .json

  CargarComprasBatch:
    handler: src/CargarComprasBatch.handler
    events:
      - s3:
          bucket: farmacia-compras-dc-456-${sls:stage}
          event: s3:ObjectCreated:*
          rules:
            - prefix: cargas/
            - suffix: .json

  Docs:
    handler: src/Docs.handler
    events:
      - http:
          path: docs
          method: get
          cors: true

  DocsUI:
    handler: src/DocsUI.handler
    events:
      - http:
          path: docs-ui
          method: get
          cors: true

resources:
  Resources:
    ComprasDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COMPRAS_TABLE}
        AttributeDefinitions:
          - AttributeName: alumno_id
            AttributeType: S
          - AttributeName: compra_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: fecha
            AttributeType: S
        KeySchema:
          - AttributeName: alumno_id
            KeyType: HASH
          - AttributeName: compra_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
        GlobalSecondaryIndexes:
          - IndexName: tenant-fecha-index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: fecha
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    S3BucketFarmaciaCompras:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: farmacia-compras-dc-456-${sls:stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
          
    ComprasCrawler:
      Type: AWS::Glue::Crawler
      DependsOn: S3BucketFarmaciaCompras
      Properties:
        Name: ${self:provider.environment.GLUE_CRAWLER_NAME}
        Role: ${self:provider.iam.role}
        DatabaseName: compras_database_${sls:stage}
        Targets:
          S3Targets:
            - Path: s3://${self:provider.environment.S3_BUCKET}/compras/
        SchemaChangePolicy:
          UpdateBehavior: LOG
          DeleteBehavior: LOG

package:
  include:
    - src/openapi.yaml
