org: dylancabezas
service: api-compras

provider:
  name: aws
  runtime: python3.10
  memorySize: 1024
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::744127473797:role/LabRole
  environment:
    COMPRAS_TABLE: t_compras_${sls:stage}
    TOKENS_TABLE: t_tokens_acceso-${sls:stage}
    S3_BUCKET: farmacia-compras-dc
    GLUE_CRAWLER_NAME: compras-crawler

functions:
  RegistrarCompra:
    handler: src/RegistrarCompra.handler
    events:
      - http:
          path: compras/registrar
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "headers": {
                    #foreach($h in $input.params().header.keySet())
                    "$h":"$util.escapeJavaScript($input.params().header.get($h))"#if($foreach.hasNext),#end
                    #end
                  },
                  "body": $input.json('$')
                }
          response:
            statusCodes:
              200:
                pattern: ''
                template: $input.body

  ListarCompras:
    handler: src/ListarCompras.handler
    events:
      - http:
          path: compras/listar
          method: get
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "headers": {
                    #foreach($h in $input.params().header.keySet())
                    "$h":"$util.escapeJavaScript($input.params().header.get($h))"#if($foreach.hasNext),#end
                    #end
                  }
                }
          response:
            statusCodes:
              200:
                pattern: ''
                template: $input.body

  ActualizarCompras:
    handler: src/ActualizarCompras.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - ComprasDynamoDBTable
              - StreamArn
          batchSize: 1
          startingPosition: LATEST

  EjecutarCrawler:
    handler: src/EjecutarCrawler.handler
    events:
      - s3:
          bucket: farmacia-compras-dc
          event: s3:ObjectCreated:*
          rules:
            - prefix: compras/
            - suffix: .json

resources:
  Resources:
    ComprasDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_compras_${sls:stage}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: alumno_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: alumno_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
